### ISSUE TITLE
Confusion about the Equation (2) in the paper.

### ISSUE THREAD

**Issue by imzhangyd** [talbenha/cell-tracker-gnn#10]
![image](https://github.com/talbenha/cell-tracker-gnn/assets/39505533/49bab762-5b2c-4ea8-9e82-bb315db5c06e)
![image](https://github.com/talbenha/cell-tracker-gnn/assets/39505533/91857236-df25-4bcd-8715-439b91e96801)

I'm puzzled why the superscript of the 'z' vector here is not 'l-1,' as according to Figure 2b, the input to the PDN-Conv module is 'Z(l-1).

**Comment by talbenha** [comment]
you are right, it's probably a typo or leftover from previous version
