### ISSUE TITLE
Pretrained models missing from releases

### ISSUE THREAD

**Issue by msschwartz21** [talbenha/cell-tracker-gnn#2]
I would like to use the pretrained models submitted to the cell tracking challenge, but they seem to be missing from the releases tab. Is there another way to gain access to the models?

**Comment by talbenha** [comment]
Hi @msschwartz21 , 
As detailed in the readme file, 
The submitted software and pretrained models to the cell tracking challenge are available at the Releases: https://github.com/talbenha/cell-tracker-gnn/releases

Please see the 'software.zip' file under the assets in the above page.

**Comment by msschwartz21** [comment]
Thanks for getting back to me! There aren't any releases included in the link above.
<img width="1063" alt="Screen Shot 2022-11-28 at 11 06 52 AM" src="https://user-images.githubusercontent.com/20373588/204360290-6ec91f9e-6bbd-4267-bf77-7d8ed375c51d.png">

**Comment by talbenha** [comment]
@msschwartz21 Thanks for pointing out, it was in draft mode so I could observe it from my side only.. Please try and let me know if it works for you

**Comment by msschwartz21** [comment]
That worked! Thank you!
