### ISSUE TITLE
Obtaining tracks from the predictions

### ISSUE THREAD

**Issue by somas193** [talbenha/cell-tracker-gnn#3]
Hello, I was trying the training_example notebook on Colab and maybe I missed something in the documentation but, it's not clear how to obtain the tracks during inference. I checked the postprocess_clean.py script and it seems the tracks are computed but not saved into a file on the disk. Please let me know how can this be resolved.

**Comment by talbenha** [comment]
@somas193 Thank you for your message! You are correct in noting that the tracks are not saved as a file on the disk. However, in the 'postprocess_clean.py' script, we do save the label maps (segmentation maps) that assign a specific label to each cell across all frames. This is done to comply with the metric computation settings for the cell tracking challenge.

To obtain the tracks that were used for the visualizations in our paper, we parsed these maps in Matlab. While this code is not currently provided in our repository, we welcome contributions through a pull request that would allow us to implement it in Python. Please let us know if you need any further assistance or if you have any questions.
