### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by 19904465540** [talbenha/cell-tracker-gnn#5]
run_train_metric_learning.py
TypeError: cannot assign 'pytorch_metric_learning.utils.common_functions.Identity' as child module 'fc' (torch.nn.Module or None expected)

**Comment by talbenha** [comment]
Hello @19904465540 
Thank you for reaching out and providing the error message. To assist you better, could you please provide the following details:

- The full command used to execute run_train_metric_learning.py.
- The version of PyTorch and the pytorch_metric_learning library you are using.
- The full error log and stack trace you received when encountering the error.

With this information, we'll do our best to assist you to resolve the error.

**Comment by talbenha** [comment]
closing because of no response - feel free to open it.
