### ISSUE TITLE
4 digit sequence length failure 

### ISSUE THREAD

**Issue by SamHawkens2** [talbenha/cell-tracker-gnn#6]
Hello!
While running Google colab notebook, I recognised that the .csv files from run_feature_extract.py got overwritten as soon as I used more than 1000 frames (0-999).

I found the following lines in the preprocess_seq2graph where it seems like only three digit image lableling is supported. I can change it from 3 to 4 and it works, but it would be nice to know if this leads to more failures downstream in other functions. 

It would be nice to use it with any possible humber of frames. 

        if im_path is not None: 
             flag = False 
             im_num = im_path.split(".")[-2][-3:] 
         if mask_path is not None: 
             flag = False 
             mask_num = mask_path.split(".")[-2][-3:] 
         if result_path is not None: 
             flag = False 
             result_num = result_path.split(".")[-2][-3:]

Thanks for the help!

Kind regards,

Fabian

**Comment by talbenha** [comment]
Hey @SamHawkens2 , 

It indeed seems to be not the best solution to read the files, sorry for that. This code was written long ago and these days I would use the following code:
```python
from pathlib import Path

Path('/root/dir/sub/file.ext').stem
``` 
with casting to the required number. 

please feel free to make a Pull Request for the corresponding changes and I will review it and add merge it to the code.

If you have more questions - please feel free to write me here.
