### ISSUE TITLE
Where is the code to modify the mask of the segmentation?

### ISSUE THREAD

**Issue by pie2cookie** [talbenha/cell-tracker-gnn#7]
Thanks for uploading the code.
The mask of the segmentation has been modified，which is not needed to me. Where is the code of the function?

**Comment by talbenha** [comment]
Hi @pie2cookie 
Thanks for you question, I don't fully understand what you mean and what you ask for. If you can be more specific, it can assist me to understand and help you. what modified mask you'r looking for?

**Comment by talbenha** [comment]
this issue was closed, if you have more question please don't hesitate
