### ISSUE TITLE
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (30812x12 and 128x64)`

### ISSUE THREAD

**Issue by 19904465540** [talbenha/cell-tracker-gnn#8]
Hello，when running run this error occurred.
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (30812x12 and 128x64)`
Can help me solve this problem？Thanks.

**Comment by talbenha** [comment]
hi @19904465540 
thanks for you question, it seems like the input you provide doesn't match the model expected dimension (probably in some MLP model). 
unfortunately it's hard to understand where and why this error happens, please provide full Traceback so I can assist.

**Comment by ruveydayilmaz0** [comment]
Hello, I had the same problem. I think the configs were configured for the Fluo-N2DH-SIM+ dataset which has images of size 628x690. When I try to use images of a different shape (700x1100 for Fluo-N2DH-HeLa for instance) I get this error for  the script run.py. Could you tell which parameters to change in the config files to be able to work with this image shape?
