### ISSUE TITLE
Have you tried some multi-object tracking methods developed for pedestrians or cars?

### ISSUE THREAD

**Issue by imzhangyd** [talbenha/cell-tracker-gnn#9]
Hi, thanks for your wonderful work. I've learned there are many multi-object tracking methods developed for pedestrians or cars. I'm curious to know if you have tried them in cell tracking and what the results were like?

**Comment by talbenha** [comment]
hi, thanks for you question
we focus mainly on comparison to cell tracking methods setting since pedestrian or vehicle tracking requires many adaption such as treating cell mitosis
